from django.urls import path
from .views import (
    RegisterView,
    ItemSubmissionView,
    MyTokenObtainPairView,
    ExpertListView,
    SubmissionListView,
    EcoTipListCreateView,
    EcoTipDetailView,
    JobRequestListCreateView,
    JobRequestRespondView,
    JobRequestAdminActionView,
    LocationListView,
    SkillListView,
    AdminDashboardSummaryView,
    AdminSubmissionListView,
    AdminSubmissionActionView,
    AdminExpertListView,
    AdminExpertVerifyView,
    SuggestionKnowledgeListCreateView,
    SuggestionKnowledgeDetailView,
)
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('submit-item/', ItemSubmissionView.as_view(), name='submit-item'),
    path('submissions/', SubmissionListView.as_view(), name='submission-list'),
    path('my-items/', SubmissionListView.as_view(), name='my-items'),
    path('experts/', ExpertListView.as_view(), name='expert-list'),
    path('eco-tips/', EcoTipListCreateView.as_view(), name='eco-tip-list-create'),
    path('eco-tips/<int:tip_id>/', EcoTipDetailView.as_view(), name='eco-tip-detail'),
    path('locations/', LocationListView.as_view(), name='location-list'),
    path('skills/', SkillListView.as_view(), name='skill-list'),
    path('admin/dashboard-summary/', AdminDashboardSummaryView.as_view(), name='admin-dashboard-summary'),
    path('admin/submissions/', AdminSubmissionListView.as_view(), name='admin-submission-list'),
    path('admin/submissions/<int:submission_id>/action/', AdminSubmissionActionView.as_view(), name='admin-submission-action'),
    path('admin/experts/', AdminExpertListView.as_view(), name='admin-expert-list'),
    path('admin/experts/<int:user_id>/verify/', AdminExpertVerifyView.as_view(), name='admin-expert-verify'),
    path('admin/knowledge-base/', SuggestionKnowledgeListCreateView.as_view(), name='admin-knowledge-base-list-create'),
    path('admin/knowledge-base/<int:entry_id>/', SuggestionKnowledgeDetailView.as_view(), name='admin-knowledge-base-detail'),
    path('job-requests/', JobRequestListCreateView.as_view(), name='job-request-list-create'),
    path('job-requests/<int:request_id>/respond/', JobRequestRespondView.as_view(), name='job-request-respond'),
    path('job-requests/<int:request_id>/admin-action/', JobRequestAdminActionView.as_view(), name='job-request-admin-action'),
]
